name: Build backend

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

jobs:
  host:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - uses: Swatinem/rust-cache@v2

      - name: Clippy
        run: |
          cargo clippy \
            -p backend \
            --all-targets

      - name: Build
        run: |
          cargo build \
            -p backend

      - name: Test
        run: |
          cargo test \
            -p backend